### ISSUE TITLE
`coord_capped_cart()` reverts axis tick length adjustments

### ISSUE THREAD

**Issue by thomas-neitmann** [stefanedwards/lemon#19]
I would like to increase the axis tick length in my plots like this (I made it extreme for emphasis).

```r
 p <- ggplot(mtcars, aes(hp, mpg)) +
  geom_point() +
  theme_classic() +
  theme(axis.ticks.length.x = unit(5, "mm"))
p
```
![image](https://user-images.githubusercontent.com/11788080/74187185-55448200-4c4c-11ea-954f-e0ff09b53ab1.png)

However, when I add `coord_capped_cart()` the tick length reverts to the theme's default length.
```r
p + coord_capped_cart(bottom = "right")
```
![image](https://user-images.githubusercontent.com/11788080/74187284-89b83e00-4c4c-11ea-9fb4-34330b35a00d.png)

**Comment by stefanedwards** [comment]
Apparently resolved with v. 0.4.6 (commit d013a187).
