### ISSUE TITLE
Axis line functionality broken in ggplot2 3.3.0

### ISSUE THREAD

**Issue by mdeber** [stefanedwards/lemon#20]
Hi, 
It looks like the newest ggplot2 release (3.3.0) has broken lemon's axis functionality (https://cran.r-project.org/web/packages/ggplot2/news/news.html). Reverting to ggplot2 3.2.1 resolved the issue. I'm using lemon 0.4.2.
Best of luck,
Mike

**Comment by stefanedwards** [comment]
Sorry for the long, long wait. These issues are fixed with the release of version 0.4.6 (pending approval on CRAN) with commit fd42de399b60fb72070700437042a8ca9e6f0511.

Try installing this version with `devtools::install_github('stefanedwards/lemon')`.
