### ISSUE TITLE
Issue with next ggplot2 release

### ISSUE THREAD

**Issue by thomasp85** [stefanedwards/lemon#25]
In the coming ggplot2 v3.3.1 we fixed a bug in the panel naming so they are now correctly reference the row and column they are located at. This, unfortunately, breaks one of lemon examples:

# lemon

<details>

* Version: 0.4.4
* Source code: https://github.com/cran/lemon
* URL: https://github.com/stefanedwards/lemon
* BugReports: https://github.com/stefanedwards/lemon/issues
* Date/Publication: 2020-04-03 16:00:18 UTC
* Number of recursive dependencies: 66

Run `cloud_details(, "lemon")` for more info

</details>

## Newly broken

*   checking examples ... ERROR
    ```
    ...
    The following objects are masked from ‘package:lemon’:
    
        CoordCartesian, element_render
    
    > dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
    > (d <- ggplot(dsamp, aes(carat, price)) +
    +  geom_point(aes(colour = clarity)))
    > 
    > reposition_legend(d + theme(legend.position='bottom'), 'bottom right')
    > 
    > # To change the orientation of the legend, use theme's descriptors.
    > reposition_legend(d + theme(legend.position='bottom'), 'top left')
    > 
    > # Use odd specifications, here offset the legend with half its height from the bottom.
    > reposition_legend(d + theme(legend.position='bottom'), x=0.3, y=0, just=c(0, -0.5))
    > 
    > # For using with facets:
    > reposition_legend(d + facet_grid(.~cut), 'top left', panel = 'panel-3-1')
    Error in reposition_legend(d + facet_grid(. ~ cut), "top left", panel = "panel-3-1") : 
      Could not find panel named `panel-3-1`.
    Execution halted
    ```

We plan to release ggplot2 in two weeks and hope you'll be able to fix the example in advance. Please reach out if you have any questions

**Comment by stefanedwards** [comment]
I've updated the examples using the branch `patch-ext-site`, and submitted the update to CRAN. For the future, I would appreciate if you made a note of your commit/branch in the issue, as it would make it easier for me to find your update to check against.

Hope you enjoyed the nice Pinse-weather!

**Comment by thomasp85** [comment]
Has lemon been accepted to CRAN? My recent revdepcheck shows that the issue is still alive.

If I don't give a branch you can assume the master branch - don't know why you ended up in patch-ext-site 🙂

**Comment by stefanedwards** [comment]
Yes, it finally went through yesterday. You should match lemon v. 0.4.5.

**Comment by thomasp85** [comment]
Great - that was around the time I ran the checks so I just missed it. Thanks
