### ISSUE TITLE
coord_capped_cart() throwing error after recent update

### ISSUE THREAD

**Issue by ObGDK** [stefanedwards/lemon#29]
Hi,

First off. THANK YOU for the `lemon` package. 

Since I recently updated most of my packages, I haven't been able to use the `lemon::coord_capped_cart()` with ggplot.

I am getting the following error: _"Error in if (guides$x$position == position) { : argument has the length zero"_

I've tried to reinstall all packages and only loading `tidyverse`, `ggplot` and `lemon`, but still getting the same error.

Cheers,
Steffen

**Comment by stefanedwards** [comment]
Thanks

It was an issue after ggplot2 was updated to v. 3.4.0. These issues are fixed with the release of version 0.4.6 (pending approval on CRAN) with commit fd42de399b60fb72070700437042a8ca9e6f0511.

Try installing this version with `devtools::install_github('stefanedwards/lemon')`.
